---

- name: Install
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - apache2

# Ensure that the certificate private keys allow for "named owner/group" ACL 
# entries to give specific non-root services access to them.
- name: Allow Group-Based Access to Certificate Private Keys
  copy:
    src: files/acme_perm
    dest: /var/lib/acme/conf/perm
    owner: acme
    group: acme
    mode: u=rw,g=r,o=r
  become: true
  # This doesn't need to be run in production, as the justdavis-ansible.git
  # plays take care of it.
  when: is_test
  register: copy_acme_perm
- name: Run acmetool to Apply Permissions Changes
  command: /usr/bin/acmetool --batch
  become: true
  become_user: acme
  when: copy_acme_perm.changed

- file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rwx,o=rx
  become: yes
  with_items:
    - "/var/apache2/rpstourney.com"
    - "/var/apache2/rpstourney.com/logs"
    - "/var/apache2/rpstourney.com/www"

- name: Configure the Ports and IPs for Apache
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes
  # This doesn't need to be run in production, as the justdavis-ansible.git
  # plays take care of it.
  when: is_test
  notify:
    - apache-restart

- apache2_module:
    state: present
    name: "{{ item }}"
  become: yes
  with_items:
    - ssl
    # Used to proxy Jenkins and other apps:
    - [proxy, proxy_http, headers]
  notify:
    - apache-restart

- template:
    src: shared-ssl.conf
    dest: "/etc/apache2/conf-available/ssl.conf"
    mode: u=rw,g=rw,o=r
  become: yes
  # This doesn't need to be run in production, as the justdavis-ansible.git
  # plays take care of it.
  when: is_test
  notify:
    - apache-reload

- command: "/usr/sbin/a2enconf ssl.conf"
  args:
    creates: "/etc/apache2/conf-enabled/ssl.conf"
  become: yes
  # This doesn't need to be run in production, as the justdavis-ansible.git
  # plays take care of it.
  when: is_test
  notify:
    - apache-reload

- template:
    src: rpstourney-ssl.conf
    dest: "/etc/apache2/sites-available/rpstourney-ssl.conf"
    mode: u=rw,g=rw,o=r
  become: yes
  notify:
    - apache-reload

- command: "/usr/sbin/a2ensite rpstourney-ssl.conf"
  args:
    creates: "/etc/apache2/sites-enabled/rpstourney-ssl.conf"
  become: yes
  notify:
    - apache-reload
