---

##
# This role assumes and requires that the justdavis.com 'apache_server' role has already been run.
# Accordingly, it assumes that Apache and certbot are already installed and properly configured.
##

- name: Import Tasks to Configure Apache
  ansible.builtin.import_tasks: configure.yml

- ansible.builtin.import_tasks: test.yml
  tags: test
