---

- name: Configure RPS Tourney Webapp
  ansible.builtin.template:
    src: rps-webapp-config.xml.j2
    dest: /var/lib/tomcat9/conf/rps-webapp-config.xml
    owner: root
    group: tomcat
    mode: u=rw,g=r,o=
  become: true
  notify:
    - "Restart Service 'tomcat9'"

- name: Create Tomcat Deployment Directory for RPS Tourney
  ansible.builtin.file:
    path: /var/lib/tomcat9/rps-tourney-apps
    state: directory
    owner: tomcat
    group: tomcat
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Create Tomcat Context for RPS Tourney Webapp
  ansible.builtin.copy:
    content: |
      <Context
        docBase="/var/lib/tomcat9/rps-tourney-apps/rps-tourney-webapp.war"
        reloadable="true"
      />
    dest: /var/lib/tomcat9/conf/Catalina/localhost/ROOT.xml
    owner: root
    group: tomcat
    mode: u=rw,g=r,o=
  become: true

- name: Deploy RPS Tourney Webapp
  ansible.builtin.copy:
    src: ../rps-tourney-webapp/target/rps-tourney-webapp-{{ rps_version }}.war
    dest: /var/lib/tomcat9/rps-tourney-apps/rps-tourney-webapp.war
    owner: tomcat
    group: tomcat
    mode: u=rw,g=r,o=r
  become: true
