---

- name: Configure RPS Tourney Webapp
  template:
    src: templates/rps-webapp-config.xml.j2
    dest: /var/lib/tomcat8/conf/rps-webapp-config.xml
    owner: root
    group: tomcat8
    mode: u=rw,g=r,o=
  become: true
  notify:
    - "Restart Service 'tomcat8'"

- name: Create Tomcat Deployment Directory for RPS Tourney
  file:
    path: /var/lib/tomcat8/rps-tourney-apps
    state: directory
    owner: tomcat8
    group: tomcat8
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Create Tomcat Context for RPS Tourney Webapp
  copy:
    content: |
      <Context
        docBase="/var/lib/tomcat8/rps-tourney-apps/rps-tourney-webapp.war"
        path=""
        reloadable="true"
      />
    dest: /var/lib/tomcat8/conf/Catalina/localhost/ROOT.xml
    owner: root
    group: tomcat8
    mode: u=rw,g=r,o=
  become: true

- name: Deploy RPS Tourney Webapp
  copy:
    src: ../rps-tourney-webapp/target/rps-tourney-webapp-{{ rps_version }}.war
    dest: /var/lib/tomcat8/rps-tourney-apps/rps-tourney-webapp.war
    owner: tomcat8
    group: tomcat8
    mode: u=rw,g=r,o=r
  become: true
