---

- name: Install Tomcat Dependencies
  ansible.builtin.package:
    name:
      - openjdk-8-jre-headless
    state: present
  become: true

- name: Install Tomcat 9.x
  ansible.builtin.package:
    name:
      - tomcat9
    state: present
  become: true
  register: package_tomcat

- name: Remove Default Tomcat Root Content
  ansible.builtin.file:
    path: /var/lib/tomcat9/webapps/ROOT
    state: absent
  become: true
  when: package_tomcat.changed

- name: Configure Tomcat Defaults
  ansible.builtin.template:
    src: defaults_tomcat9.j2
    dest: /etc/default/tomcat9
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart Service 'tomcat9'"

- name: Configure Tomcat server.xml
  ansible.builtin.template:
    src: server.xml.j2
    dest: /var/lib/tomcat9/conf/server.xml
    owner: root
    group: tomcat
    mode: u=rw,g=r,o=
  become: true
  notify:
    - "Restart Service 'tomcat9'"

# If Tomcat was stopped before this play was ran and the config wasn't modified,
# we need to start it back up before we're done.
- name: Ensure Tomcat is Started
  ansible.builtin.service:
    name: tomcat9
    state: started
  become: true
