---
# This playbook configures `eddings.justdavis.com` to host the RPS Tourney
# application and deploys the latest build of that application to it.
#
# Usage: This playbook can be run, as follows:
#
#     $ ./ansible-playbook-wrapper site.yml

- hosts: eddings.justdavis.com
  name: Install RPS Tourney Dependencies
  tags: ['platform']
  gather_facts: true
  tasks:
    - ansible.builtin.import_role: name=postgresql_server
    - ansible.builtin.import_role: name=tomcat
    - ansible.builtin.import_role: name=apache

- hosts: eddings.justdavis.com
  name: Deploy RPS Tourney
  tags: ['deploy']
  gather_facts: true
  tasks:
    - name: Include Maven-Generated Variables
      ansible.builtin.include_vars:
        file: target/config/project.yml
    - ansible.builtin.import_role: name=rps_service
    - ansible.builtin.import_role: name=rps_webapp
